[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = ["-1"]

[font]
size = 12

[font.bold]
family = "CaskaydiaCove NF"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove NF"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove NF"
style = "Italic"

[font.normal]
family = "CaskaydiaCove NF"
style = "Regular"

[window]
dynamic_title = true

[window.dimensions]
columns = 0
lines = 0

[window.position]
x = 0
y = 0

[window.padding]
x = 25
y = 15

#opacity = 1.0
#dynamic_padding = false
#decorations = "none"
# startup_mode = "SimpleFullscreen"

[scrolling]
history = 50000
multiplier = 3


[keyboard]
bindings = [
  # Copy (Ctrl+Shift+C)
  { key = "C", mods = "Control|Shift", action = "Copy" },

  # Paste (Ctrl+Shift+V)
  { key = "V", mods = "Control|Shift", action = "Paste" },

  # New window (Ctrl+Shift+N)
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },

  # Quit (Ctrl+Shift+Q)
  { key = "Q", mods = "Control|Shift", action = "Quit" },

  # Increase font size (Ctrl + =)
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },

  # Decrease font size (Ctrl + -)
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },

  # Reset font size (Ctrl + 0)
  { key = "Key0", mods = "Control", action = "ResetFontSize" }
]
